/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'authorUsername' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'postId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Post = IDL.Record({
  'id' : IDL.Text,
  'authorUsername' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'timestamp' : Time,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const SocialProfile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'image' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'image' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'countFollowers' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'countFollowing' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'createComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Comment], []),
  'createPost' : IDL.Func([IDL.Text, ExternalBlob], [Post], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [SocialProfile],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByPostId' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getPostById' : IDL.Func([IDL.Text], [Post], ['query']),
  'getProfileById' : IDL.Func([IDL.Text], [SocialProfile], ['query']),
  'getSelfProfile' : IDL.Func([], [SocialProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProfiles' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(SocialProfile)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFollow' : IDL.Func([IDL.Principal], [], []),
  'toggleLike' : IDL.Func([IDL.Text], [Post], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [SocialProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'authorUsername' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'postId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Post = IDL.Record({
    'id' : IDL.Text,
    'authorUsername' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'timestamp' : Time,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const SocialProfile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'image' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'image' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'countFollowers' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'countFollowing' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'createComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Comment], []),
    'createPost' : IDL.Func([IDL.Text, ExternalBlob], [Post], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [SocialProfile],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByPostId' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getFeed' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getPostById' : IDL.Func([IDL.Text], [Post], ['query']),
    'getProfileById' : IDL.Func([IDL.Text], [SocialProfile], ['query']),
    'getSelfProfile' : IDL.Func([], [SocialProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProfiles' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(SocialProfile)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFollow' : IDL.Func([IDL.Principal], [], []),
    'toggleLike' : IDL.Func([IDL.Text], [Post], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [SocialProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };