/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : string,
  'authorUsername' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Post {
  'id' : string,
  'authorUsername' : string,
  'author' : Principal,
  'likes' : bigint,
  'timestamp' : Time,
  'caption' : string,
  'image' : ExternalBlob,
}
export interface SocialProfile {
  'id' : string,
  'bio' : string,
  'displayName' : string,
  'author' : Principal,
  'timestamp' : Time,
  'image' : ExternalBlob,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'image' : ExternalBlob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'countFollowers' : ActorMethod<[Principal], bigint>,
  'countFollowing' : ActorMethod<[Principal], bigint>,
  'createComment' : ActorMethod<[string, string, string], Comment>,
  'createPost' : ActorMethod<[string, ExternalBlob], Post>,
  'createProfile' : ActorMethod<[string, string, ExternalBlob], SocialProfile>,
  'deleteComment' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByPostId' : ActorMethod<[string], Array<Comment>>,
  'getFeed' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getPostById' : ActorMethod<[string], Post>,
  'getProfileById' : ActorMethod<[string], SocialProfile>,
  'getSelfProfile' : ActorMethod<[], SocialProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProfiles' : ActorMethod<[[] | [string]], Array<SocialProfile>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleFollow' : ActorMethod<[Principal], undefined>,
  'toggleLike' : ActorMethod<[string], Post>,
  'updateProfile' : ActorMethod<[string, string, ExternalBlob], SocialProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];